version: '3.4'
services:
  #Nginx Service

  Figaro:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=figaro"
      - "traefik.frontend.rule=Host:figaro.localhost"
      - "traefik.port=80" 
    networks:
      - traefik
    volumes:
      - ./indexF1.html:/usr/share/nginx/html/index.html

#Docker Networks
networks:
  app-network:
    driver: bridge
  traefik:
    external: 
      name: traefik_webgateway

  