version: '3.4'
services:
  #Nginx Service
  Figaro1:
    image: nginx:alpine
    container_name: Figaro1
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    networks:
      - app-network
    volumes: 
      - ./indexF1.html:/usr/share/nginx/html/index.html
    
  Figaro2:
    image: nginx:alpine
    container_name: Figaro2
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    networks:
      - app-network
    volumes: 
      - ./indexF2.html:/usr/share/nginx/html/index.html

  Gorafi1:
    image: nginx:alpine
    container_name: Gorafi1
    restart: unless-stopped
    tty: true
    ports:
      - "8091:80"
    networks:
      - app-network
    volumes: 
      - ./indexG1.html:/usr/share/nginx/html/index.html
 
  Gorafi2:
    image: nginx:alpine
    container_name: Gorafi2
    restart: unless-stopped
    tty: true
    ports:
      - "8092:80"
    networks:
      - app-network
    volumes: 
      - ./indexG2.html:/usr/share/nginx/html/index.html

#Docker Networks
networks:
  app-network:
    driver: bridge