version: '3.4'
services:
  #Nginx Service
  
  Gorafi:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.backend=gorafi"
      - "traefik.frontend.rule=Host:gorafi.localhost"
      - "traefik.port=80"
    networks:
      - traefik
    volumes:
      - ./indexG1.html:/usr/share/nginx/html/index.html

#Docker Networks
networks:
  app-network:
    driver: bridge
  traefik:
    external: 
      name: traefik_webgateway

  